version: "3"

services:
  flarum:
    build: .
    image: docker-flarum/flarum:latest
    container_name: flarum
    env_file:
      - flarum.env
    volumes:
      - /home/admin/flarum/assets:/flarum/app/public/assets
      - /home/admin/flarum/extensions:/flarum/app/extensions
      - /home/admin/flarum/storage/logs:/flarum/app/storage/logs
      - /home/admin/flarum/nginx:/etc/nginx/flarum
    ports:
      - 3080:8888
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=12345678
    volumes:
      - /home/admin/flarum/mysql/db:/var/lib/mysql
